//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProvImageMarkup.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\Users\\OBogdan\\Documents\\Visual Studio 2015\\Projects\\ProvImageMarkup\\")]
        public string defDbPath {
            get {
                return ((string)(this["defDbPath"]));
            }
            set {
                this["defDbPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Test/10000/книга учета №-3")]
        public string defCur {
            get {
                return ((string)(this["defCur"]));
            }
            set {
                this["defCur"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\terminalsrv-sav\\ORT\\OI\\2016\\12\\29\\images\\КП038Б-1С1\\ORIG\\Передача_001_КП038Б-1С" +
            "1\\книга учета №-3")]
        public string defReplace {
            get {
                return ((string)(this["defReplace"]));
            }
            set {
                this["defReplace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FilePath")]
        public string defcolname {
            get {
                return ((string)(this["defcolname"]));
            }
            set {
                this["defcolname"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Khaki")]
        public global::System.Drawing.Color defColor {
            get {
                return ((global::System.Drawing.Color)(this["defColor"]));
            }
            set {
                this["defColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10.0")]
        public decimal defBorder {
            get {
                return ((decimal)(this["defBorder"]));
            }
            set {
                this["defBorder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color defTextColor {
            get {
                return ((global::System.Drawing.Color)(this["defTextColor"]));
            }
            set {
                this["defTextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Arial Black, 20.25pt, style=Bold")]
        public global::System.Drawing.Font defFont {
            get {
                return ((global::System.Drawing.Font)(this["defFont"]));
            }
            set {
                this["defFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int defOtst {
            get {
                return ((int)(this["defOtst"]));
            }
            set {
                this["defOtst"] = value;
            }
        }
    }
}
